version: '3.7'

services:
  web:
    build: .
    command: uwsgi --http :8000 --chdir=django_search --module django_search.wsgi
    environment:
      - DJANGO_DEBUG
      - SECRET_KEY
      - DJANGO_ALLOWED_HOSTS
      - DJANGO_DATABASE
      - DJANGO_DATABASE_PASS
    network_mode: "host"